import React from 'react'

export default function Home() {
  return (
    <div>
      <h1>Home</h1>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Impedit vel at, repellat similique velit molestiae voluptatibus aliquid sed, amet quasi quo enim fugiat hic. Recusandae pariatur quidem quo aliquam corporis accusamus dolorum aliquid consequuntur facilis iure. Ullam illum, eum beatae placeat ratione vel porro exercitationem iste omnis quae corrupti expedita asperiores, vero ab reiciendis adipisci itaque voluptas sint. Nobis deserunt, unde, modi exercitationem animi adipisci necessitatibus soluta, nesciunt eaque alias vel aperiam neque quia dolore laudantium? Incidunt tempora est dolor adipisci quis ab reprehenderit? Voluptate, quos omnis. Eaque facilis voluptatem fuga doloremque. Eum voluptates maxime, aliquid voluptatibus accusantium cupiditate recusandae aperiam impedit soluta, at tempora saepe qui perspiciatis ab minima ut aliquam officia molestiae ad! Earum, sit. Ex, incidunt in sit eligendi consectetur praesentium, voluptatibus facere, numquam consequatur maxime perferendis. Quod, explicabo. Reiciendis, ullam? Aliquam aspernatur soluta consequuntur quisquam quis, sed in laudantium accusamus tempora tenetur a iste officia voluptatum dolor odio similique obcaecati quibusdam doloribus repellat error laboriosam sunt perferendis saepe recusandae. Aliquam commodi fuga voluptates quam ratione exercitationem tenetur ducimus obcaecati ea atque expedita quis quidem quae, impedit id culpa est? Labore dignissimos sequi a! Eum magni labore ut illum facilis nostrum, minima laudantium perspiciatis inventore vero architecto totam minus maiores! Consequuntur impedit assumenda quod! Earum voluptatibus tempore ipsam optio suscipit iure aut nostrum quasi nesciunt cumque molestiae temporibus debitis, dolorem ducimus voluptatum eligendi adipisci facilis recusandae quisquam. Ducimus maiores natus praesentium fugit numquam sapiente, perferendis blanditiis consectetur aperiam qui ullam architecto facere aspernatur expedita et repellendus distinctio dolores fugiat vero cum hic. Officiis fugiat obcaecati nostrum alias accusantium minima temporibus beatae aut deserunt illo impedit eos, in est, natus incidunt vel sunt, distinctio corrupti magni porro commodi ullam architecto quas sequi. Repellat ex dolore expedita voluptatem id delectus assumenda maxime distinctio excepturi saepe labore quibusdam voluptatibus repellendus odio consectetur provident, laboriosam ipsa et quasi, explicabo obcaecati! Eos quo molestiae iusto sequi voluptatum labore facilis illum adipisci molestias inventore quos officia iure earum rerum sunt, ducimus perspiciatis quia reiciendis! Sapiente sequi tempora, veritatis provident repellat quasi aspernatur quis libero consectetur dolorum! Veritatis aliquid autem dolores similique ut. Harum?</p>
    </div>
  )
}
